# Generated by Django 2.1 on 2018-08-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(default=True, max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(default=True, max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(default=True, max_length=70, verbose_name='Email')),
                ('password', models.CharField(default=True, max_length=30, verbose_name='Password')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
