# Generated by Django 2.1 on 2018-08-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180807_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=70, unique=True, verbose_name='Email'),
        ),
    ]
